void tis_init(void);
_Bool tispunct(char c);
_Bool tisspace(char c);
_Bool tisdigit(char c);
_Bool tiscntl(char c);
_Bool tisupper(char c);
_Bool tislower(char c);
_Bool tisxdigit(char c);
_Bool tisblank(char c);
_Bool tisalpha(char c);
_Bool tisalnum(char c);
_Bool tisgraph(char c);
_Bool tisprint(char c);
